--- 

- name: Install SSM Agent using YUM
  yum:
    name: https://s3.amazonaws.com/ec2-downloads-windows/SSMAgent/latest/linux_amd64/amazon-ssm-agent.rpm
    state: present
    disable_gpg_check: yes
  notify: Restart SSM Agent service
