---

- name: Install Ansible collections
  include_tasks: common/install_ansible_collections.yaml

- name: Install dependencies for RedHat
  include_tasks: rhel/install_deps.yaml
  when: ansible_distribution == "RedHat"

- name: Install dependencies for OEL
  include_tasks: oel/install_deps.yaml
  when: ansible_distribution == "OracleLinux"

- name: Show distribution
  debug: 
    msg: "{{ ansible_distribution }}"

- name: Install dependencies for SUSE
  include_tasks: suse/install_deps.yaml
  when: ansible_distribution == "SUSE"

- name: Check if AWS CLI is available
  include_tasks: common/check_aws_cli.yaml

- name: Install SSM
  include_tasks: rhel/install_ssm.yaml
  
- name: Install AWS SAP Data Provider for RedHat
  include_tasks: rhel/install_data_provider_rhel.yaml
  
- name: Install EFS utils
  include_tasks: rhel/install_efs_utils.yaml
